import 'tailwindcss/tailwind.css';
import AnalyticsProvider from './_components/AnalyticsProvider';

export const metadata = {
  title: 'Sable.',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='bg-black text-slate-50'>
        {children}
      <AnalyticsProvider/>
      </body>
    </html>
  )
}
